path: /mocking
title: OpenAPI Mocking
color: grey-darkest
relatedTags:
  - blog-mocking
hero:
  subtitle: Build APIs and accelerate API development with instant mock servers
  title: OpenAPI Powered Mock Servers
featureSection:
  actionBar:
    buttons:
      - href: 'https://next.stoplight.io/'
        title: Get Started
    enabled: true
    text: 'Want to mock your API? '
  description: >-
    Mocking your API with Stoplight is your API design’s perfect companion.
    Powered by Prism, the instant [mock server](/mock-api-guide/basics/) routes incoming requests to
    example responses or dynamically generates examples on the fly based on your
    OpenAPI Specification (formerly known as Swagger).
  features:
    - description: >-
        Supercharge any OpenAPI Specification with Stoplight Mocking. Once you
        have created or imported your OpenAPI Specification, you have access to
        an instant mock server, which automatically reloads when your
        specification changes. A mock API simulates the behavior of a real API
        allowing collaboration and feedback on your API design.
      image: /images/mocking_instant.png
      shortName: Instant Mocking
      title: Instant Mock Server
      titleURL: /mocking/server
    - description: >-
        With Mocking, you can accelerate the development of new APIs. Teams can
        work in tandem before the API is available through virtualization.
        Stoplight’s mock servers can virtualize internal and external APIs
        within your platform with dynamic responses generated from your JSON
        Schema, which can be run locally or hosted with Stoplight.
      image: /images/mocking_virtualization.png
      shortName: Virtualization
      title: Virtualization
    - description: >-
        Validates requests and responses against your OpenAPI Specification.
        Simulates real server behavior by automatically validating incoming
        request headers, query strings, and request bodies against your OpenAPI
        Specification.
      image: /images/mocking_request_validation.png
      shortName: Request Validation
      title: Automatic Request Validation
    - description: >-
        Need a mocked response property to always be a random future date? No
        problem. Mocking can extend your OpenAPI Specification with scripts
        before or after traffic reaches your mock server. Write scripts for more
        [complex mocking behavior](/mock-api-guide/advanced/), custom validations, and much more.
      image: /images/mocking_customization.png
      shortName: Customizable
      title: Customizable
  title: OpenAPI Mocking
meta:
  description: >-
    Mocking your API with Stoplight is your API design’s perfect companion.
    Powered by Prism, the instant mock server routes incoming requests to
    example responses or dynamically generates examples on the fly based on your
    OpenAPI Specification (formerly known as Swagger).
  favicon: /images/mark_light_bg.png
  title: REST API mocking service and server by Prism | Stoplight
  twitter:
    description: >-
      Mocking your API with Stoplight is your API design’s perfect companion.
      Powered by Prism, the instant mock server routes incoming requests to
      example responses or dynamically generates examples on the fly based on
      your OpenAPI Specification (formerly known as Swagger).
    image: /images/mocking_instant.png
    title: REST API mocking service and server by Prism | Stoplight
    username: '@stoplightio'
